import { prisma } from "@/lib/prisma";
import RefundsClient from "./_components/RefundsClient";
import type { RefundRowItem } from "./_components/RefundRow";

export default async function AdminRefundsPage() {
  const bookings = await prisma.booking.findMany({
    where: {
      refundStatus: "PENDING",
      refundAmount: {
        gt: 0,
      },
    },
    include: {
      user: {
        select: {
          id: true,
          name: true,
          email: true,
        },
      },
      homestay: {
        select: {
          id: true,
          name: true,
          village: true,
          district: true,
          state: true,
          cancellationPolicy: true,
        },
      },
    },
    orderBy: {
      cancelledAt: "desc",
    },
  });

  const refunds: RefundRowItem[] = bookings.map((b) => ({
    bookingId: b.id,

    refundAmount: b.refundAmount!.toString(),
    refundStatus: b.refundStatus,

    cancelledAt: b.cancelledAt!.toISOString(),
    checkIn: b.checkIn.toISOString(),

    guest: {
      id: b.user.id,
      name: b.user.name,
      email: b.user.email,
    },

    homestay: {
      id: b.homestay.id,
      name: b.homestay.name,
      village: b.homestay.village,
      district: b.homestay.district,
      state: b.homestay.state,
      cancellationPolicy: b.homestay.cancellationPolicy,
    },
  }));

  return (
    <div className="h-full flex flex-col py-8 px-24">
      <div className="mb-8">
        <h1 className="text-3xl font-semibold text-mitti-dark-brown">
          Refunds
        </h1>
        <p className="mt-1 text-sm text-mitti-dark-brown/70">
          Process guest refunds generated by cancellation policies
        </p>
      </div>

      <RefundsClient refunds={refunds} />
    </div>
  );
}
