/* eslint-disable @next/next/no-img-element */

import * as React from "react";

export function BasePdfLayout({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        width: "100%",
        height: 1000,
        backgroundColor: "#F4F1E1",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily:
          "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial",
      }}
    >
      <div
        style={{
          width: 760,
          height: "100%",
          padding: 32,
          boxSizing: "border-box",
        }}
      >
        {/* White card */}
        <div
          style={{
            height: "100%",
            backgroundColor: "#ffffff",
            borderRadius: 18,
            padding: 32,
            boxShadow: "0 10px 28px rgba(0,0,0,0.08)",
            boxSizing: "border-box",
          }}
        >
          {children}
        </div>

        {/* Footer always below card */}
        <div
          style={{
            textAlign: "center",
            fontSize: 10,
            color: "#8C8E98",
            marginTop: 12,
          }}
        >
          Generated by MITTI · Rural Homestay Booking Platform
        </div>
      </div>
    </div>
  );
}
